Models/Data/Book.cs
using Microsoft.Extensions.Localization;

namespace bookish.Models.Data;

public class Book
{
    public required int Id {get; set;}
    public required string ISBN { get; set;}
    public required string Title { get; init;}

    public required string Author {get; init;}

    public required int YearOfPublication {get; set;}

    public required string Publisher {get; set;}

    public required string ImageURLS {get; set;}

    public required string ImageURLM {get; set;}
    public required string ImageURLL {get; set;}

    public List<Copy> Copies {get; set; } = [];
    
    public override string ToString()
    {
        return $"Title: {Title}, Author: {Author}, Year of Publish: {YearOfPublication}, Publisher: {Publisher}";
    }
}

Models/Data/BookTrans.cs
using Microsoft.Extensions.Localization;

namespace bookish.Models.Data;

public class BookTrans
{
    public required string ISBN { get; set;}
    public required string Title { get; init;}

    public required string Author {get; init;}

    public required string YearOfPublication {get; set;}

    public required string Publisher {get; set;}

    public required string ImageURLS {get; set;}

    public required string ImageURLM {get; set;}
    public required string ImageURLL {get; set;}

}

Models/Data/Copy.cs
using System.ComponentModel.DataAnnotations.Schema;
using bookish.Enums;

namespace bookish.Models.Data;

public class Copy
{
    public int Id { get; set; }
    public int BookId { get; set;}
    [ForeignKey(nameof(BookId))]
    public Book Book { get; set;} = null!;

    public Condition Condition {get; set;} = Condition.Pristine;

    public List<Loan> LoanHistory {get; set; } = [];

    public Boolean HasLiveLoan => LoanHistory.Any(loan => loan.DateReturned == null);

    public Loan? LiveLoan => LoanHistory.SingleOrDefault(loan => loan.DateReturned == null);
}

Models/Data/Loan.cs
using System.ComponentModel.DataAnnotations.Schema;
using bookish.Constants;

namespace bookish.Models.Data;

public class Loan
{
    public int Id {get; set; }
    public int MemberId { set; get;}
    [ForeignKey("MemberId")]
    public Member Member { set; get;} = null!;

    public int CopyId {get; set;}
    [ForeignKey(nameof(CopyId))]
    public Copy Copy {get; set;} = null!;
    public DateOnly DateBorrowed { get; set;} = DateOnly.FromDateTime(DateTime.Today);

    public DateOnly DateDueBack { get; set; } = DateOnly.FromDateTime(DateTime.Today).AddDays(LoanConstants.DefaultLoanLength);
    public DateOnly? DateReturned { get; set;}
    
}

Models/Data/Member.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace bookish.Models.Data;


public class Member
{
    public required int Id {get; set;}
    public required string UserName {get; set;}

    public  List<Loan> LoanHistory {get; set; } = [];
    [NotMapped]
    public List<Loan> ActiveLoans => LoanHistory.Where(loan => loan.DateReturned == null).ToList();

}

Models/View/BookViewModel.cs
using bookish.Models.Data;

namespace bookish.Models.View;

public class BookViewModel
{
    public required List<Book> Books {get; set;}
}

Models/View/ErrorViewModel.cs
namespace bookish.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/View/MemberViewModel.cs
using bookish.Models.Data;

namespace bookish.Models.View;

public class MemberViewModel
{
    public required List<Member> Members {get; set;}
}

Controllers/BookController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using bookish.Models.Data;
using bookish.Models.View;
using Microsoft.EntityFrameworkCore;

namespace bookish.Controllers;

public class BookController : Controller

{
    private readonly Library _library;
    private readonly ILogger<BookController> _logger;

    public BookController(ILogger<BookController> logger, Library library)
    {
        _library = library;
        _logger = logger;
    }

    public IActionResult Navigation()
    {
        return View();
    }


    public IActionResult ViewAll( int pageNum = 0)
    {
        var books = _library.Books.ToList();
        var pageSize = 15;
        var count = _library.Books.Count();

        var viewModel = books.Skip(pageSize*pageNum).Take(pageSize).ToList();
        var bookData = new BookViewModel
        {
            Books = viewModel,
        };
        ViewBag.MaxPage = (count/pageSize) - (count % pageSize==0 ? 1: 0);
        ViewBag.Page = pageNum;

        return View(bookData);
    }

    public IActionResult BookDetail([FromRoute] int id)
    {
        var matchingBook = _library.Books.Include(book => book.Copies)
                                        .SingleOrDefault(book=> book.Id == id);
        if(matchingBook == null)
        {
            return NotFound();
        }
        return View(matchingBook);
    }


}

Controllers/CopyController.cs
using bookish.Models.Data;
using bookish.Models.View;
using bookish.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace bookish.Controllers;

public class CopyController : Controller

{
    private readonly Library _library;
    private readonly ILogger<CopyController> _logger;

    public CopyController(ILogger<CopyController> logger, Library library)
    {
        _library = library;
        _logger = logger;
    }

    [HttpGet]
    public IActionResult AddCopy([FromRoute] int id)

    {
        var matchingBook = _library.Books.Include(book => book.Copies)
                            .SingleOrDefault(book => book.Id == id);    
                                            
        if(matchingBook == null)
        {
            return NotFound();
        }
        return View(matchingBook);
    }

    [HttpPost]
    public IActionResult AddCopy([FromRoute] int id, [FromForm] Copy copy)
    {
        copy.BookId = id;
        _library.Copies.Add(copy);
        _library.SaveChanges();
        return RedirectToAction(nameof(AddCopy));
    }

}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using bookish.Models;

namespace bookish.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Books()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/MemberController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using bookish.Models.Data;
using bookish.Models.View;
using Microsoft.EntityFrameworkCore;

namespace bookish.Controllers;

public class MemberController : Controller

{
    private readonly Library _library;
    private readonly ILogger<MemberController> _logger;

    public MemberController(ILogger<MemberController> logger, Library library)
    {
        _library = library;
        _logger = logger;
    }

    public IActionResult Navigation()
    {
        return View();
    }


    public IActionResult ViewAll( int pageNum = 0)
    {
        var members = _library.Members.ToList();
        var pageSize = 15;
        var count = _library.Members.Count();

        var viewModel = members.Skip(pageSize*pageNum).Take(pageSize).ToList();
        var memberData = new MemberViewModel
        {
            Members = viewModel,
        };
        ViewBag.MaxPage = (count/pageSize) - (count % pageSize==0 ? 1: 0);
        ViewBag.Page = pageNum;

        return View(memberData);
    }

    public IActionResult MemberDetail([FromRoute] int id)
    {
        var matchingMember = _library.Members.Include(member => member.LoanHistory)
                                            .ThenInclude(loan => loan.Copy)
                                            .ThenInclude(copy => copy.Book)
                                        .SingleOrDefault(member=> member.Id == id);
        if(matchingMember == null)
        {
            return NotFound();
        }
        return View(matchingMember);
    }


}

Views/Book/BookDetail.cshtml
@using bookish.Models.Data;
@using bookish.Enums;
@model Book;

@{
    ViewData["Title"] = "@Model.Title";
}

<div>
    <div>
        <img src="@Model.ImageURLL" alt="Book Cover Image of @Model.Title">
        <h2>Title:@Model.Title</h2>
        <h3>By @Model.Author</h3>
        <p>Current Number of Copies: @Model.Copies.Count()</p>
        <a class="btn btn-dark btn-small" asp-controller="Copy" asp-action="AddCopy" asp-route-id="@Model.Id">Add New Copy</a>
    </div>

    <div>
        <table class="table">
            <tr>
                <th scope="col">Copy ID</th>
                <th scope="col">Copy Condition</th>
                <th scope="col">Copy Borrowed</th>
                <th scope="col">Update Copy Condition</th>
            </tr>

            @{
                foreach(var copy in Model.Copies)
                {
                    <tr>
                        <td>@copy.Id</td>
                        <td>@copy.Condition</td>
                        <td>@copy.HasLiveLoan</td>
                        <td>Update Copy Condition</td>
                    </tr>
                }
            }


        </table>
    </div>
</div>

Views/Book/Navigation.cshtml
@{
    ViewData["Title"] = "Books";
}

<div>
    <h1>How Can We Help You</h1>
    <ul>
        <li><a asp-area="" asp-controller="Book" asp-action="ViewAll">View Books</a></li>
        <li><a asp-area="" asp-controller="Book" asp-action="Register">Register A New Book</a></li>

    </ul>
</div>

Views/Book/ViewAll.cshtml
@using bookish.Models.View;
@model BookViewModel;

@{
    ViewData["Title"] = "View all books";
}

<div>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">ISBN</th>
                <th scope="col">Image</th>
                <th scope="col">Title</th>
                <th scope="col">Author</th>
                <th scope="col">Year Of Publication</th>
                <th scope="col">Publisher</th>
                <th scope="col">More</th>
            </tr>
        </thead>

        <tbody>
            @{
                foreach(var book in Model.Books)
                {
                    <tr>
                        <th scope="col">
                            <a class="btn btn-link" asp-area="" asp-controller="Book" asp-action="BookDetail" asp-route-id=@book.Id> @book.Id</a>
                        </th>                        
                        <td>
                            <a class="btn btn-link" asp-area="" asp-controller="Book" asp-action="BookDetail" asp-route-id=@book.Id> @book.ISBN</a>
                        </td>
                        <td><img src="@book.ImageURLS" alt="Image of book @book.Title"></td>
                        <td>
                            <a class="btn btn-link" asp-area="" asp-controller="Book" asp-action="BookDetail" asp-route-id=@book.Id> @book.Title</a>
                        </td>
                        <td>@book.Author</td>
                        <td>@book.YearOfPublication</td>
                        <td>@book.Publisher</td>
                        <td>
                            <a class="btn btn-dark btn-sm" asp-area="" asp-controller="Copy" asp-action="AddCopy" asp-route-id=@book.Id> Add Copy</a>
                        </td>
                    </tr>  
                }
            }

        </tbody>

    </table>
    <div>
        
        @if (ViewBag.Page > 0)
        {
            <a href="@Url.Action("ViewAll", new { pageNum = ViewBag.Page - 1 })" 
            class="btn btn-default">
                &laquo; Prev
            </a>
        }
        @if (ViewBag.Page < ViewBag.MaxPage)
        {
            <a asp-controller="Book" asp-action="ViewAll" asp-route-pageNum="@(ViewBag.Page + 1)"
            class="btn btn-default">
                Next &raquo;
            </a>
        }

    </div>

</div>

Views/Copy/AddCopy.cshtml
@using bookish.Models.Data;
@using bookish.Enums;
@model Book;

@{
    ViewData["Title"] = "Add Copy";
}

<div>
    <div>
        <h1>Add New Copy For: </h1>
        <img src="@Model.ImageURLL" alt="Book Cover Image of @Model.Title">
        <h2>Title:@Model.Title</h2>
        <h3>By @Model.Author</h3>
        <p>Current Number of Copies: @Model.Copies.Count()</p>
    </div>

    <div>
        <form method="post">
            <p Condition>Select the condition of the new copy:</p>
            @{
                foreach (var condition in Enum.GetValues<Condition>())
                {
                    <input type="radio" id="@condition" name="Condition" value="@condition">
                    <label for="@condition">@condition</label><br>
                }
            }
            <br>
            <button class="btn btn-primary btn-sm" type="submit">Submit</button>
            <a class="btn btn-primary btn-sm" asp-controller="Book" asp-action="BookDetail" asp-route-id=@Model.Id>Back to Book Detail</a>
        </form>
    </div>

</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Penguin Library</h1>
    <img src="https://images.pexels.com/photos/1046125/pexels-photo-1046125.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="picture of a library">
</div>

Views/Member/MemberDetail.cshtml
@using bookish.Models.Data;
@model Member;

@{
    ViewData["Title"] = "@Model.Username";
}

<div>
    <div>
        <h2>@Model.UserName</h2>
        <a class="btn btn-dark btn-small" asp-controller="Member" asp-action="MemberDetail" asp-route-id="@Model.Id">Edit</a>
    </div>

    <div>
        <h3>Loan History of @Model.UserName</h3>
        <table>
            <tr>
                <th scope="col">Loan ID</th>
                <th scope="col">Book Title</th>
                @* <th scope="col">Copy ID</th> *@
                <th scope="col">Start Date </th>
                <th scope="col">Due Return Date </th>
                <th scope="col">Return Date</th>
            </tr>

            @{
                foreach(var loan in Model.LoanHistory)
                {
                    <tr>
                        <td>@loan.Id</td>
                        <td>@loan.Copy.Book.Title</td>
                        @* <td>@loan.CopyId</td> *@
                        <td>@loan.DateBorrowed</td>
                        <td>@loan.DateDueBack</td>
                        <td>@loan.DateReturned</td>
                    </tr>
                }
            }


        </table>
    </div>
</div>

Views/Member/Navigation.cshtml
@{
    ViewData["Title"] = "Books";
}

<div>
    <h1>How Can We Help You</h1>
    <ul>
        <li><a asp-area="" asp-controller="Member" asp-action="ViewAll">View Members</a></li>
        <li><a asp-area="" asp-controller="Member" asp-action="">Register A New Member</a></li>
    </ul>
</div>

Views/Member/ViewAll.cshtml
@using bookish.Models.View;
@model MemberViewModel;

@{
    ViewData["Title"] = "View all members";
}

<div>
    <table class="table">
        <thead class="thead-dark" >
            <tr>@*  row1 *@
                <th scope="col">ID</th>
                <th scope="col">Username</th>
                @* <th scope="col">Active Loans</th> *@
                <th scope="col">Detail</th>
                <th scope="col">Edit</th>
            </tr>
        </thead>

        <tbody>
            @{
                foreach(var member in Model.Members)
                {
                    <tr>
                        <th scope="row">
                            <a class="btn btn-link" asp-area="" asp-controller="Member" asp-action="MemberDetail" asp-route-id=@member.Id> @member.Id</a>
                        </th>
                        <td>
                            <a class="btn btn-link" asp-area="" asp-controller="Member" asp-action="MemberDetail" asp-route-id=@member.Id> @member.UserName</a>
                        </td>
                        <td>
                            <a class="btn btn-dark btn-sm" asp-area="" asp-controller="Member" asp-action="MemberDetail" asp-route-id=@member.Id> Detail</a>
                        </td>
                        <td>
                            <a class="btn btn-dark btn-sm" asp-area="" asp-controller="Member" asp-action="MemberDetail" asp-route-id=@member.Id> Edit</a>
                        </td>
                    </tr>  
                }
            }

        </tbody>

    </table>
    <div>
        
        @if (ViewBag.Page > 0)
        {
            <a href="@Url.Action("ViewAll", new { pageNum = ViewBag.Page - 1 })" 
            class="btn btn-default">
                &laquo; Prev
            </a>
        }
        @if (ViewBag.Page < ViewBag.MaxPage)
        {
            <a asp-controller="Book" asp-action="ViewAll" asp-route-pageNum="@(ViewBag.Page + 1)"
            class="btn btn-default">
                Next &raquo;
            </a>
        }

    </div>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - bookish</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/bookish.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bookish</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Navigation">Books</a>
                        </li>   
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="Navigation">Members</a>
                        </li>                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - bookish - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>